import { MainSkillData, DetailedSkills, SkillDetails } from "@/types/skills_t";
import { NextResponse } from "next/server";

const mainData: MainSkillData[] = [
  { name: "Frontend", value: 60, color: "#2DA7C7" },
  { name: "Backend", value: 30, color: "#2ED6A1" },
  { name: "DevOps", value: 10, color: "#6BFF6B" },
];

const detailedSkills: DetailedSkills = {
  React: [
    { skill: "Hooks", proficiency: 90, color: "#61dafb" },
    { skill: "Context API", proficiency: 85, color: "#61dafb" },
    { skill: "Components", proficiency: 95, color: "#61dafb" },
    { skill: "State Management", proficiency: 88, color: "#61dafb" },
    { skill: "Testing", proficiency: 75, color: "#61dafb" },
    { skill: "Performance Optimization", proficiency: 80, color: "#61dafb" },
    { skill: "Accessibility", proficiency: 30, color: "#61dafb" },
    { skill: "Routing", proficiency: 85, color: "#61dafb" },
    { skill: "Redux", proficiency: 90, color: "#61dafb" },
    { skill: "Zustand", proficiency: 90, color: "#61dafb" },
    { skill: "Responsive Design", proficiency: 90, color: "#61dafb" },
    { skill: "Debugging", proficiency: 90, color: "#61dafb" },
    { skill: "Security", proficiency: 90, color: "#61dafb" },
  ],
  ReactNative: [
    { skill: "Android", proficiency: 90, color: "#61dafb" },
    { skill: "IOS", proficiency: 85, color: "#61dafb" },
    { skill: "Components", proficiency: 95, color: "#61dafb" },
    { skill: "State Management", proficiency: 88, color: "#61dafb" },
    { skill: "Testing", proficiency: 75, color: "#61dafb" },
    { skill: "Performance Optimization", proficiency: 80, color: "#61dafb" },
    { skill: "Routing", proficiency: 90, color: "#61dafb" },
    { skill: "Native Bridging", proficiency: 85, color: "#61dafb" },
    { skill: "XCode", proficiency: 90, color: "#61dafb" },
    { skill: "Android Studio", proficiency: 90, color: "#61dafb" },
    { skill: "Play store", proficiency: 90, color: "#61dafb" },
    { skill: "App Store", proficiency: 90, color: "#61dafb" },
    { skill: "Expo", proficiency: 90, color: "#61dafb" },
    { skill: "Bare React Native", proficiency: 90, color: "#61dafb" },
    { skill: "Crossplatfrom Designs", proficiency: 90, color: "#61dafb" },
    { skill: "Debugging", proficiency: 90, color: "#61dafb" },
  ],
  Android: [
    { skill: "Java", proficiency: 70, color: "#3DDC84" },
    { skill: "Kotlin", proficiency: 70, color: "#3DDC84" },
    { skill: "XML Layouts", proficiency: 80, color: "#3DDC84" },
    { skill: "Android Studio", proficiency: 90, color: "#3DDC84" },
    { skill: "Gradle", proficiency: 75, color: "#3DDC84" },
    { skill: "Material Design", proficiency: 85, color: "#3DDC84" },
    { skill: "MVVM", proficiency: 80, color: "#3DDC84" },
    { skill: "Architectural Components", proficiency: 80, color: "#3DDC84" },
    { skill: "Debugging", proficiency: 90, color: "#3DDC84" },
  ],
  "Next.js": [
    { skill: "Hooks", proficiency: 90, color: "#61dafb" },
    { skill: "Context API", proficiency: 85, color: "#61dafb" },
    { skill: "Components", proficiency: 95, color: "#61dafb" },
    { skill: "State Management", proficiency: 88, color: "#61dafb" },
    { skill: "CSR/SSR/SSG", proficiency: 85, color: "#61dafb" },
    { skill: "API Routes", proficiency: 90, color: "#61dafb" },
    { skill: "Routing", proficiency: 92, color: "#61dafb" },
  ],
  Design: [
    { skill: "Figma", proficiency: 90, color: "#FF61F6" },
    { skill: "Tailwind", proficiency: 80, color: "#FF61F6" },
    { skill: "Styled Components", proficiency: 80, color: "#FF61F6" },
    { skill: "Material UI", proficiency: 70, color: "#FF61F6" },
    { skill: "UI/UX Design", proficiency: 85, color: "#FF61F6" },
    { skill: "Responsive Design", proficiency: 90, color: "#FF61F6" },
    { skill: "Accessibility", proficiency: 60, color: "#FF61F6" },
  ],
  TypeScript: [
    { skill: "Types & Interfaces", proficiency: 90, color: "#3178c6" },
    { skill: "Generics", proficiency: 80, color: "#3178c6" },
    { skill: "Decorators", proficiency: 60, color: "#3178c6" },
    { skill: "Advanced Types", proficiency: 90, color: "#3178c6" },
    { skill: "Configuration", proficiency: 90, color: "#3178c6" },
  ],
  "Node.js": [
    { skill: "Express.js", proficiency: 90, color: "#339933" },
    { skill: "Middleware", proficiency: 85, color: "#339933" },
    { skill: "Authentication", proficiency: 80, color: "#339933" },
    { skill: "File System", proficiency: 75, color: "#339933" },
    { skill: "Async/Await", proficiency: 92, color: "#339933" },
    { skill: "REST API's", proficiency: 92, color: "#339933" },
    { skill: "GraphQL", proficiency: 70, color: "#339933" },
    { skill: "Postgres", proficiency: 80, color: "#339933" },
    { skill: "Redis", proficiency: 70, color: "#339933" },
    { skill: "SQL", proficiency: 80, color: "#339933" },
    { skill: "NoSQL", proficiency: 60, color: "#339933" },
    { skill: "MongoDB", proficiency: 60, color: "#339933" },
  ],
  Python: [
    { skill: "Django", proficiency: 80, color: "#3776ab" },
    { skill: "API Development", proficiency: 70, color: "#3776ab" },
    { skill: "Scripting", proficiency: 90, color: "#3776ab" },
    { skill: "Postgres", proficiency: 80, color: "#339933" },
    { skill: "Redis", proficiency: 70, color: "#339933" },
    { skill: "SQL", proficiency: 80, color: "#339933" },
    { skill: "NoSQL", proficiency: 60, color: "#339933" },
    { skill: "MongoDB", proficiency: 60, color: "#339933" },
  ],
  AWS: [
    { skill: "EC2", proficiency: 80, color: "#ff9900" },
    { skill: "S3", proficiency: 85, color: "#ff9900" },
    { skill: "Lambda", proficiency: 60, color: "#ff9900" },
    { skill: "RDS", proficiency: 70, color: "#ff9900" },
    { skill: "CloudFront", proficiency: 65, color: "#ff9900" },
    {skill: "Cognito", proficiency: 60, color: "#ff9900" },
    {skill: "Amplify", proficiency: 70, color: "#ff9900" },
  ],
  Docker: [
    { skill: "Containerization", proficiency: 90, color: "#2496ed" },
    { skill: "Docker Compose", proficiency: 85, color: "#2496ed" },
    { skill: "Kubernetes", proficiency: 60, color: "#2496ed" },
  ],
  "Git & GitHub": [
    { skill: "Version Control", proficiency: 90, color: "#f05032" },
    { skill: "Branching", proficiency: 85, color: "#f05032" },
    { skill: "Merging", proficiency: 80, color: "#f05032" },
    { skill: "Pull Requests", proficiency: 90, color: "#f05032" },
    { skill: "GitHub Actions", proficiency: 75, color: "#f05032" },
  ],
  "Testing": [
    { skill: "Jest", proficiency: 80, color: "#c21325" },
    { skill: "React Testing Library", proficiency: 75, color: "#c21325" },
    { skill: "Cypress", proficiency: 70, color: "#c21325" },
    { skill: "Unit Testing", proficiency: 85, color: "#c21325" },
    { skill: "Integration Testing", proficiency: 80, color: "#c21325" },
    { skill: "End-to-End Testing", proficiency: 75, color: "#c21325" },
  ],
  "Deployment": [
    { skill: "Vercel", proficiency: 70, color: "#000000" },
    { skill: "Heroku", proficiency: 80, color: "#430098" },
    { skill: "AWS", proficiency: 70, color: "#ff9900" },
    { skill: "Docker", proficiency: 75, color: "#2496ed" },
    { skill: "Play store", proficiency: 90, color: "#f05032" },
    { skill: "App store", proficiency: 90, color: "#f05032" },
  ],
};

const skillDetails: SkillDetails = {
  Frontend: [
    "React",
    "React Native",
    "Android",
    "Next.js",
    "TypeScript",
    "Tailwind CSS",
    "HTML5",
    "CSS3",
    "JavaScript",
  ],
  Backend: [
    "Node.js",
    "Python",
    "PostgreSQL",
    "MongoDB",
    "REST APIs",
    "GraphQL",
  ],
  DevOps: ["Docker", "AWS", "CI/CD", "Kubernetes", "Git", "GitHub Actions"],
};

export async function GET() {
  const data = {
    mainData: mainData,
    detailedSkills: detailedSkills,
    skillDetails: skillDetails,
  };

  return NextResponse.json(data);
}
